en:
  languageCode: en
  languageName: English
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  contentDir: content/en

# Uncomment for multilingual sites, and customize the following config.
de:
  languageCode: de
  languageName: German
  contentDir: content/de
  title: Anstiftung ✏️